// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Kredensial Supabase diambil dari environment variables.
// Nilai VITE_* akan diekspos ke bundle client-side — ini adalah anon key
// yang memang boleh publik, TAPI keamanan data bergantung pada RLS di Supabase.
// JANGAN pernah menaruh service_role key di variabel VITE_*.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "[Mind MHIRC] VITE_SUPABASE_URL dan VITE_SUPABASE_ANON_KEY harus diisi di file .env.local. " +
    "Salin .env.example ke .env.local dan isi nilainya."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});