name: Supabase Deploy Migrations

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/config.toml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (includes Supabase CLI)
        run: npm install --no-audit --no-fund

      - name: Supabase login
        run: npx supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link Supabase project
        run: npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Deploy migrations
        run: npx supabase db push
